### ISSUE TITLE
Question about the pretrained models

### ISSUE THREAD

**Issue by ZhengyuZhang96** [YingqianWang/LF-InterNet#10]
Hi, author. I really appreciate your interesting work! But I would like to know which dataset is used to train the pretrained models that you provide? or you train the model with all the data in 6 datasets? 

looking forward to your reply!

**Comment by YingqianWang** [comment]
Thanks for your attention to our work. The pretrained models in this repo were trained using all the 6 datasets as mentioned in the ECCV paper. We also released the pretrained models trained on the first 5 datasets (exclude STFlytro) in our LF-DFnet repo. We suggest to use the first 5 datasets for training and test since the STFlytro dataset has a very large number of Lytro scenes and can degrade the performance of algorithms on the HCI and STFgantry datasets.

**Comment by ZhengyuZhang96** [comment]
Thanks for your reply！
