### ISSUE TITLE
When I run the test code, the computer is crashed??

### ISSUE THREAD

**Issue by dreamhua82** [YingqianWang/LF-InterNet#2]
Dear Yingqian,

Thanks for your work.
I download the test code and your test datasets & pretrained model. But when I run the code, The computer will crashed.
The PC is as like this:  GPU: 1080Ti, 8GB memory, i7 CPU, and os is Ubuntu 18.04.
This will be happen when I run it on another PC with win7 os.
Any help about this problem?

**Comment by YingqianWang** [comment]
Thanks for your comments. I guess, that is probably due to the insuffient CPU memory of your PC. Since we did not crop the testing light field into sub light fields during inference, our models are tested on CPU and a larger CPU memory (more than 32GB) is needed while running these models, especially under a large angular resolution.  

We have already fixed this issue (i.e., perform LF splitting and use GPU for inference) and will share our scheme in our coming work LF-DFnet.
