### ISSUE TITLE
Asking for help about the compared methods?

### ISSUE THREAD

**Issue by dreamhua82** [YingqianWang/LF-InterNet#7]
Hi, I have a question to ask you. Are all the compared methods needs to retrained on the same datasets as your paper stated?
How to compute the biscubic and the SISR methods's  PSNR and SSIM on one LF image? 

Hope for your kindly reply,
Regards

**Comment by YingqianWang** [comment]
In our ECCV paper, only LFSSR was retrained since its official model was trained under the BD degradation (blur and downsampling), and other methods in this paper were directly tested using their released codes and pretrained models (although training set was different). Note that, we have retrained most of these compared methods in our recent TIP paper (link: https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9286855). However, in the TIP paper, we did not use the STFlytro dataset since it has a large number of Lytro LFs and may break the balance among different LF data.

We use bicubic and SISR methods to super-resolve all the SAIs in an LF, and calculate the PSNR and SSIM of each SAI separately. Then, the PSNR and SSIM of a scene is calculated by averaging the scores over all its SAIs. Finally, the PSNR and SSIM of a dataset is calculated by averaging the scores over all the scenes.
